INSERT INTO PROPIETARIOS (APELLIDOS, NOMBRES) VALUES
	('LUQUE ZELADA', 'DANTE FABIAN'),
    ('GUERRERO', 'JUAN');

INSERT INTO MASCOTAS (PROPIETARIO_ID, TIPO, NOMBRE, COLOR, GENERO, ESTA_VIVO) VALUES
	(1, 'PERRO', 'TUMOR', 'BLANCO', 'M', TRUE),
    (2, 'GATO', 'GARFIULT', 'NEGRO', 'M', TRUE),
    (2, 'PERRO', 'ARIANA', 'VERDE', 'F', TRUE),
    (1, 'GATO', 'CON BOTAS', 'MARRON', 'M', TRUE);
